version: '3.8'
services:
    java-maven-app:
      #image: ${IMAGE}
      image: 561656302811.dkr.ecr.eu-central-1.amazonaws.com/k0938261-training:latest
      ports:
        - 8080:8080
    postgres:
      image: postgres:15
      ports:
        - 5432:5432
      environment:
        - POSTGRES_PASSWORD=my-pwd